[package]
name = "app"
version = "0.1.0"
authors = ["torresashjian <migueltorreslopez@gmail.com>"]
edition = "2018"

[dependencies]
serde_derive = "1.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
trigger = { path = "../trigger" }
